using System;
using System.Collections.Generic;

namespace ProcessExplorerWeb.Core.Entities
{
    public class ProcessExplorerUserSession : Entity<Guid>
    {
        //NOTE: ID is not autogenerated !!!

        /// <summary>
        /// When did user loged in ?
        /// </summary>
        public DateTime Started { get; set; }

        public DateTime Inserted { get; set; }

        /// <summary>
        /// User loged in as ?
        /// </summary>
        public string UserName { get; set; }

        /// <summary>
        /// Operating System (LINUX / WINDOWS)
        /// </summary>
        public string OS { get; set; }


        public Guid ExplorerUserId { get; set; }
        public virtual ProcessExplorerUser ProcessExplorerUser { get; set; }


        public virtual ICollection<ProcessEntity> Processes { get; set; }
        public virtual ICollection<ApplicationEntity> Applications { get; set; }
    }
}
