//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncSoapReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityModel", Namespace="http://schemas.datacontract.org/2004/07/ProcessExplorer.Api.Soap.Models")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SyncSoapReference.SyncApplicationModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SyncSoapReference.SyncProcessModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SyncSoapReference.SyncSessionModel))]
    public partial class SecurityModel : object
    {
        
        private string JwtField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Jwt
        {
            get
            {
                return this.JwtField;
            }
            set
            {
                this.JwtField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SyncApplicationModel", Namespace="http://schemas.datacontract.org/2004/07/ProcessExplorer.Api.Soap.Models")]
    public partial class SyncApplicationModel : SyncSoapReference.SecurityModel
    {
        
        private SyncSoapReference.ApplicationInstanceModel[] ApplicationsField;
        
        private string OSField;
        
        private string SessionIdField;
        
        private System.DateTime StartedField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SyncSoapReference.ApplicationInstanceModel[] Applications
        {
            get
            {
                return this.ApplicationsField;
            }
            set
            {
                this.ApplicationsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OS
        {
            get
            {
                return this.OSField;
            }
            set
            {
                this.OSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId
        {
            get
            {
                return this.SessionIdField;
            }
            set
            {
                this.SessionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Started
        {
            get
            {
                return this.StartedField;
            }
            set
            {
                this.StartedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SyncProcessModel", Namespace="http://schemas.datacontract.org/2004/07/ProcessExplorer.Api.Soap.Models")]
    public partial class SyncProcessModel : SyncSoapReference.SecurityModel
    {
        
        private string OSField;
        
        private SyncSoapReference.ProcessInstanceModel[] ProcessesField;
        
        private string SessionIdField;
        
        private System.DateTime StartedField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OS
        {
            get
            {
                return this.OSField;
            }
            set
            {
                this.OSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SyncSoapReference.ProcessInstanceModel[] Processes
        {
            get
            {
                return this.ProcessesField;
            }
            set
            {
                this.ProcessesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId
        {
            get
            {
                return this.SessionIdField;
            }
            set
            {
                this.SessionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Started
        {
            get
            {
                return this.StartedField;
            }
            set
            {
                this.StartedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SyncSessionModel", Namespace="http://schemas.datacontract.org/2004/07/ProcessExplorer.Api.Soap.Models")]
    public partial class SyncSessionModel : SyncSoapReference.SecurityModel
    {
        
        private SyncSoapReference.ApplicationInstanceModel[] ApplicationsField;
        
        private string OSField;
        
        private SyncSoapReference.ProcessInstanceModel[] ProcessesField;
        
        private string SessionIdField;
        
        private System.DateTime StartedField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SyncSoapReference.ApplicationInstanceModel[] Applications
        {
            get
            {
                return this.ApplicationsField;
            }
            set
            {
                this.ApplicationsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OS
        {
            get
            {
                return this.OSField;
            }
            set
            {
                this.OSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SyncSoapReference.ProcessInstanceModel[] Processes
        {
            get
            {
                return this.ProcessesField;
            }
            set
            {
                this.ProcessesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId
        {
            get
            {
                return this.SessionIdField;
            }
            set
            {
                this.SessionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Started
        {
            get
            {
                return this.StartedField;
            }
            set
            {
                this.StartedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationInstanceModel", Namespace="http://schemas.datacontract.org/2004/07/ProcessExplorer.Api.Soap.Models")]
    public partial class ApplicationInstanceModel : object
    {
        
        private System.DateTime LastUseField;
        
        private string NameField;
        
        private string SessionIdField;
        
        private System.DateTime StartedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUse
        {
            get
            {
                return this.LastUseField;
            }
            set
            {
                this.LastUseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId
        {
            get
            {
                return this.SessionIdField;
            }
            set
            {
                this.SessionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Started
        {
            get
            {
                return this.StartedField;
            }
            set
            {
                this.StartedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessInstanceModel", Namespace="http://schemas.datacontract.org/2004/07/ProcessExplorer.Api.Soap.Models")]
    public partial class ProcessInstanceModel : object
    {
        
        private System.DateTime DetectedField;
        
        private string JWTField;
        
        private string NameField;
        
        private string SessionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Detected
        {
            get
            {
                return this.DetectedField;
            }
            set
            {
                this.DetectedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JWT
        {
            get
            {
                return this.JWTField;
            }
            set
            {
                this.JWTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId
        {
            get
            {
                return this.SessionIdField;
            }
            set
            {
                this.SessionIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SyncSoapReference.ISyncService")]
    public interface ISyncService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncService/Test", ReplyAction="http://tempuri.org/ISyncService/TestResponse")]
        System.Threading.Tasks.Task<string> TestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncService/SyncSession", ReplyAction="http://tempuri.org/ISyncService/SyncSessionResponse")]
        System.Threading.Tasks.Task<bool> SyncSessionAsync(SyncSoapReference.SyncSessionModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncService/SyncApplications", ReplyAction="http://tempuri.org/ISyncService/SyncApplicationsResponse")]
        System.Threading.Tasks.Task<bool> SyncApplicationsAsync(SyncSoapReference.SyncApplicationModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncService/SyncProcesses", ReplyAction="http://tempuri.org/ISyncService/SyncProcessesResponse")]
        System.Threading.Tasks.Task<bool> SyncProcessesAsync(SyncSoapReference.SyncProcessModel model);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ISyncServiceChannel : SyncSoapReference.ISyncService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SyncServiceClient : System.ServiceModel.ClientBase<SyncSoapReference.ISyncService>, SyncSoapReference.ISyncService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SyncServiceClient() : 
                base(SyncServiceClient.GetDefaultBinding(), SyncServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SyncServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SyncServiceClient.GetBindingForEndpoint(endpointConfiguration), SyncServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SyncServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SyncServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SyncServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SyncServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SyncServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> TestAsync()
        {
            return base.Channel.TestAsync();
        }
        
        public System.Threading.Tasks.Task<bool> SyncSessionAsync(SyncSoapReference.SyncSessionModel model)
        {
            return base.Channel.SyncSessionAsync(model);
        }
        
        public System.Threading.Tasks.Task<bool> SyncApplicationsAsync(SyncSoapReference.SyncApplicationModel model)
        {
            return base.Channel.SyncApplicationsAsync(model);
        }
        
        public System.Threading.Tasks.Task<bool> SyncProcessesAsync(SyncSoapReference.SyncProcessModel model)
        {
            return base.Channel.SyncProcessesAsync(model);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding))
            {

                //return new System.ServiceModel.EndpointAddress("https://localhost:44362/SyncService.asmx"); //Development
                return new System.ServiceModel.EndpointAddress("https://processexplorerfoi.azurewebsites.net/SyncService.asmx"); //Production
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SyncServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SyncServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding,
        }
    }
}
